[tool.black]
line-length = 88
target-version = ['py39', 'py310', 'py311']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | __pycache__
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
known_first_party = ["api", "config", "db", "middleware", "model", "service", "utils"]
known_third_party = ["fastapi", "pydantic", "sqlalchemy", "loguru", "uvicorn"]

[tool.mypy]
python_version = "3.9"
# base settings
warn_return_any = false
warn_unused_configs = true
show_error_codes = true

# relax type check requirements
disallow_untyped_defs = false
disallow_incomplete_defs = false
check_untyped_defs = false
disallow_untyped_decorators = false
no_implicit_optional = false

# keep useful warnings
warn_redundant_casts = false
warn_unused_ignores = false
warn_no_return = false
warn_unreachable = false
strict_equality = false

# ignore common third-party libraries
[[tool.mypy.overrides]]
module = [
    "aiomysql.*",
    "greenlet.*",
    "werkzeug.*",
    "fastapi.*",
    "pydantic.*",
    "sqlalchemy.*",
    "loguru.*",
    "uvicorn.*",
    "starlette.*",
    "pymysql.*",
]
ignore_missing_imports = true

# relax requirements for specific files
[[tool.mypy.overrides]]
module = [
    "api.*",
    "service.*",
    "model.*",
    "db.*",
    "middleware.*",
    "utils.*",
]
disallow_untyped_defs = false
disallow_incomplete_defs = false
check_untyped_defs = false
warn_return_any = false
ignore_errors = true

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = [
    "--strict-markers",
    "--strict-config",
    "--cov=.",
    "--cov-report=term-missing",
    "--cov-report=html",
    "--cov-report=xml",
]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "integration: marks tests as integration tests",
]

[tool.bandit]
exclude_dirs = ["tests"]
skips = ["B101", "B601", "B501"]
